# Site settings
title: Towards the Rising Sun
email: 116@lab0.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lab0.net" # the base hostname & protocol for your site
twitter_username: uuh116
github_username:  ununhexium

# Build settings
markdown: kramdown

# Serving
detach:  false
port:    4000
host:    192.168.2.112
baseurl: "" # does not include hostname

