#!/bin/bash
# ubuntu 15.04

sudo aptitude install ruby gem ruby2.1-dev make gcc g++ git nodejs zsh htop imagemagick

sudo chsh --shell $(which zsh) $USER


exit 0

# note for cygwin: .minttyrc to change the colors
ForegroundColour=131,148,150
BackgroundColour=0,0,0
CursorColour=220,50,47
Black=7,54,66
BoldBlack=0,43,54
Red=220,50,47
BoldRed=203,75,22
Green=0,200,132
BoldGreen=0,200,132
Yellow=204,204,102
BoldYellow=204,204,102
Blue=102,153,204
BoldBlue=102,153,204
Magenta=211,54,130
BoldMagenta=108,113,196
Cyan=42,161,152
BoldCyan=147,161,161
White=238,232,213
BoldWhite=253,246,227
BoldAsFont=no
Transparency=off
OpaqueWhenFocused=no
CursorType=block
CursorBlinks=no
Font=Consolas
FontHeight=10

