get-data:
	rsync -avru /cygdrive/r/Hubic/Data/rtw/img/ /cygdrive/r/dev/git/rtw/WebContent/img/

put-data:
	rsync -avru /cygdrive/r/dev/git/rtw/WebContent/img/ /cygdrive/r/Hubic/Data/rtw/img/

sync-data: get-data put-data

